name: Build Images

concurrency: ${{ github.ref }}

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'images/**'
      - 'scripts/**'
      # - 'builder/**'

env:
  STORAGE_ACCOUNT: contosoimagesstorage
  RESOURCE_GROUP: rg-image-builder
  SUBSCRIPTION: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  SUBNET_ID: /subscriptions/$SUBSCRIPTION/resourceGroups/$RESOURCE_GROUP/providers/Microsoft.Network/virtualNetworks/contoso-images-vnet/subnets/builders
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

    # Authenticate to Az CLI using OIDC
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # az cli installs bicep on demand the first time it's used
      # using the --async argument in the command below simultaniously invokes several commands that use bicep
      # so if bicep isn't already installed, the all initiate the install which throws a file busy error so we
      # execute an arbitrary az bicep command here (and get the latest updates in the process)
      - name: Ensure Bicep
        run: az bicep upgrade

      - name: Deploy Build ACI Containers
        run: python "./builder/build.py" --async --repository "${{ github.repositoryUrl }}" --revision "${{ github.sha }}" --token "${{ github.token }}" --storage-account "${{ env.STORAGE_ACCOUNT }}" --subnet-id "${{ env.SUBNET_ID }}"
